import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { approvedGuideSlugs, publicGuides } from "@/content/guides";
import { InstagramDashboardPage } from "@/components/guides/instagram-dashboard-page";
import { WhatIsAiPage } from "@/components/guides/what-is-ai-page";
import { AiJargonPage } from "@/components/guides/ai-jargon-page";
import { AgenticPage } from "@/components/guides/agentic-page";
import { PrivacyGuidePage } from "@/components/guides/privacy-guide-page";
import { ToolChooserPage } from "@/components/guides/tool-chooser-page";
import { ShortAnswerPage } from "@/components/guides/short-answer-page";
import { ChatGptProjectPage } from "@/components/guides/chatgpt-project-page";
import { ScheduledTaskPage } from "@/components/guides/scheduled-task-page";
import { ClaudeTaskPage } from "@/components/guides/claude-task-page";
import { ClaudeProjectsPage } from "@/components/guides/claude-projects-page";
import { GeminiDrivePage } from "@/components/guides/gemini-drive-page";
import { GeminiTasksPage } from "@/components/guides/gemini-tasks-page";
import { GrokReviewPage } from "@/components/guides/grok-review-page";
import { CopilotExcelPage } from "@/components/guides/copilot-excel-page";
import { CopilotVisibilityPage } from "@/components/guides/copilot-visibility-page";
import { PromptBuilderPage } from "@/components/guides/prompt-builder-page";
import { GrokWritingPage } from "@/components/guides/grok-writing-page";
import { DeepseekWallPage } from "@/components/guides/deepseek-wall-page";
import { DeepseekLongEditPage } from "@/components/guides/deepseek-long-edit-page";
import { KimiValuePage } from "@/components/guides/kimi-value-page";
import { KimiCodePage } from "@/components/guides/kimi-code-page";
import { ManusBrowserPage } from "@/components/guides/manus-browser-page";
import { AiBrowserPage } from "@/components/guides/ai-browser-page";
import { AiConnectionsPage } from "@/components/guides/ai-connections-page";
import { AiSkillsPage } from "@/components/guides/ai-skills-page";
import { AiSearchPage } from "@/components/guides/ai-search-page";
import { CustomerResearchPage } from "@/components/guides/customer-research-page";
import { ClaudeWorkflowPage } from "@/components/guides/claude-workflow-page";
import { DeepseekRecoveryPage } from "@/components/guides/deepseek-recovery-page";
import { DeepseekDocumentPage } from "@/components/guides/deepseek-document-page";
import { MetaMusePage } from "@/components/guides/meta-muse-page";
import { MetaMuseSavingPage } from "@/components/guides/meta-muse-saving-page";
import { ScreenRecordingPage } from "@/components/guides/screen-recording-page";
import { MistralMultilingualPage } from "@/components/guides/mistral-multilingual-page";
import { GuideAccessBoundary } from "@/components/guides/guide-access-boundary";
import { getGuidePage, guidePages, type GuidePage, type GuideSection } from "@/content/guide-page";

function excerpt(section: GuideSection): string {
  switch (section.kind) {
    case "prose": return section.paragraphs[0];
    case "cards": return section.introduction || section.items[0].body;
    case "comparison": return section.introduction || `Compare ${section.columns.join(" and ")}.`;
    case "diagram": return section.nodes[0].body;
    default: return section.introduction;
  }
}
export function generateStaticParams() {
  return approvedGuideSlugs.map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const guide = getGuidePage(slug);
  if (!guide) return {};
  const canonical = `/guides/${guide.slug}/`;
  return {
    title: guide.title,
    ...(approvedGuideSlugs.includes(slug) ? {} : { robots: { index: false, follow: false } }),
    description: guide.seoDescription,
    alternates: { canonical },
    openGraph: {
      title: guide.title,
      description: guide.seoDescription,
      url: canonical,
      type: "article",
      images: [{ url: guide.cover, width: 1280, height: 721 }],
    },
  };
}

export default async function GuideArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (!approvedGuideSlugs.includes(slug)) notFound();
  const guide = getGuidePage(slug);
  if (!guide) notFound();
  const guideModel = guide as GuidePage;
  if (slug === "instagram-content-dashboard") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><InstagramDashboardPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "what-is-ai") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><WhatIsAiPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "ai-jargon-guide") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><AiJargonPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "what-is-agentic") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><AgenticPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "what-should-you-never-share-with-ai") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><PrivacyGuidePage guide={guide} /></GuideAccessBoundary>;
  if (slug === "which-ai-tool-for-what") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><ToolChooserPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "make-chatgpt-answers-shorter") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><ShortAnswerPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "stop-chatgpt-forgetting-context") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><ChatGptProjectPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "chatgpt-scheduled-tasks") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><ScheduledTaskPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "claude") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><ClaudeTaskPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "claude-projects") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><ClaudeProjectsPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "gemini-cannot-find-drive-file") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><GeminiDrivePage guide={guide} /></GuideAccessBoundary>;
  if (slug === "gemini-google-tasks-limits") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><GeminiTasksPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "review-grok-suggestions") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><GrokReviewPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "check-copilot-excel-edits") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><CopilotExcelPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "what-can-copilot-see-at-work") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><CopilotVisibilityPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "chatgpt-screen-recording-to-process-guide") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><ScreenRecordingPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "meta-ai") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle="What is Meta Muse?" guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><MetaMusePage guide={guide} /></GuideAccessBoundary>;
  if (slug === "test-meta-muse-money-saving-task") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle="Can Muse save you money?" guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><MetaMuseSavingPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "what-is-a-prompt") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><PromptBuilderPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "get-better-professional-writing-from-grok") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><GrokWritingPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "fix-deepseek-wall-of-text") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><DeepseekWallPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "edit-long-writing-with-deepseek") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><DeepseekLongEditPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "is-kimi-worth-paying-for") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><KimiValuePage guide={guide} /></GuideAccessBoundary>;
  if (slug === "control-kimi-code-changes") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><KimiCodePage guide={guide} /></GuideAccessBoundary>;
  if (slug === "manus-browser-workflow") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><ManusBrowserPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "what-is-an-ai-browser") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><AiBrowserPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "connect-ai-to-email-files-calendar") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><AiConnectionsPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "ai-skills-worth-learning-for-work") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><AiSkillsPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "show-up-in-ai-search") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><AiSearchPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "chatgpt-customer-research-with-evidence") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><CustomerResearchPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "teach-claude-a-repeatable-workflow") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><ClaudeWorkflowPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "protect-a-long-deepseek-project") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><DeepseekRecoveryPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "test-deepseek-v4-document-work") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><DeepseekDocumentPage guide={guide} /></GuideAccessBoundary>;
  if (slug === "mistral-multilingual-research") return <GuideAccessBoundary guideSlug={guide.slug} guideTitle={guide.title} guideCover={guide.cover} guideCoverAlt={guide.coverAlt} guidePromise={guide.promise} chapters={guide.sections.length ? guide.sections.map((section) => section.heading) : guideModel.series?.part === 1 ? guideModel.series.tasks.map((task) => task.title) : ["Set it up", "Try it", "Check the result"]} previewAnswer={guide.answer.paragraphs} previewSections={guide.sections.length ? guide.sections.slice(0, 2).map((section) => ({ heading: section.heading, excerpt: excerpt(section) })) : guideModel.series?.part === 1 ? guideModel.series.tasks.slice(0, 1).map((task) => ({ heading: task.title, excerpt: task.example })) : guideModel.series?.part === 2 ? [{ heading: "First, set up your project", excerpt: guideModel.series.instructions }] : []} readingMinutes={publicGuides.find((item) => item.slug === guide.slug)?.readMinutes} variant="entry"><MistralMultilingualPage guide={guide} /></GuideAccessBoundary>;
  throw new Error(`Guide ${slug} needs an approved interactive Next.js composition before it can be built.`);
}
