// Page records for the new guides 26 to 35 (approved 28/09/2026).
// Their reading content lives in guide-batch-26-35.ts; these records give the
// library, metadata and related cards a title, cover and email tag.
import type { GuidePage } from "./guide-page";

export const newGuidePages: readonly GuidePage[] = [
  {
    slug: "stop-ai-agreeing-with-you",
    title: "Stop AI Agreeing With Everything You Say",
    promise: "Get honest feedback on your writing, a real stress test for your plans, and a standing rule that switches off the flattery.",
    cover: "/images/guides/stop-ai-agreeing-with-you.webp",
    coverAlt: "The blue robot mascot checking pages with a magnifier and a red stamp",
    seoDescription: "AI tools are built to be helpful, and agreeing feels helpful. Ask for problems before praise, give it a job that includes disagreeing, and set that rule once in your settings.",
    lumailTag: "guide-stop-ai-agreeing-with-you",
    answer: { paragraphs: ["AI tools are built to be helpful, and agreeing feels helpful. Ask for problems before praise, give it a job that includes disagreeing, and set that rule once in your settings."] },
    sections: [],
    conclusion: { heading: "", paragraphs: ["Get honest feedback on your writing, a real stress test for your plans, and a standing rule that switches off the flattery."], finishLine: "" },
    related: [],
  },
  {
    slug: "catch-ai-making-things-up",
    title: "Catch AI Making Things Up in 30 Seconds",
    promise: "Three quick checks for the three places AI mistakes hide: numbers and names, sources, and the bits it's least sure of.",
    cover: "/images/guides/catch-ai-making-things-up.webp",
    coverAlt: "The blue robot mascot measuring a printed list and marking the wrong lines in red",
    seoDescription: "Trust it like a fast new colleague: useful, but check before it goes out under your name. Three 10-second checks catch most mistakes before anyone else sees them.",
    lumailTag: "guide-catch-ai-making-things-up",
    answer: { paragraphs: ["Trust it like a fast new colleague: useful, but check before it goes out under your name. Three 10-second checks catch most mistakes before anyone else sees them."] },
    sections: [],
    conclusion: { heading: "", paragraphs: ["Three quick checks for the three places AI mistakes hide: numbers and names, sources, and the bits it's least sure of."], finishLine: "" },
    related: [],
  },
  {
    slug: "ai-quit-or-stay-decision",
    title: "Make a Quit-or-Stay Decision With 5 AI Advisors",
    promise: "Describe both options fairly, hear five very different advisors, and test the decision before you hand in any notice.",
    cover: "/images/guides/ai-quit-or-stay-decision.webp",
    coverAlt: "The blue robot mascot weighing two options on a brass balance between two presses",
    seoDescription: "AI can't decide for you, and it tends to agree with however you ask. It can help if you describe both options equally, ask five advisors with different jobs to weigh in, and turn the result into a small test.",
    lumailTag: "guide-ai-quit-or-stay-decision",
    answer: { paragraphs: ["AI can't decide for you, and it tends to agree with however you ask. It can help if you describe both options equally, ask five advisors with different jobs to weigh in, and turn the result into a small test."] },
    sections: [],
    conclusion: { heading: "", paragraphs: ["Describe both options fairly, hear five very different advisors, and test the decision before you hand in any notice."], finishLine: "" },
    related: [],
  },
  {
    slug: "is-ai-coming-for-my-job",
    title: "Check How Exposed Your Job Is to AI in 5 Minutes",
    promise: "Not a scary score. A task-by-task look at your real week, and the one skill to build next.",
    cover: "/images/guides/is-ai-coming-for-my-job.webp",
    coverAlt: "The blue robot mascot sorting cards on a conveyor past a gauge and a stop sign",
    seoDescription: "AI changes tasks, not whole jobs, at least at first. List what you actually do each week, sort each task honestly, and put your energy into the parts that need you.",
    lumailTag: "guide-is-ai-coming-for-my-job",
    answer: { paragraphs: ["AI changes tasks, not whole jobs, at least at first. List what you actually do each week, sort each task honestly, and put your energy into the parts that need you."] },
    sections: [],
    conclusion: { heading: "", paragraphs: ["Not a scary score. A task-by-task look at your real week, and the one skill to build next."], finishLine: "" },
    related: [],
  },
  {
    slug: "test-business-idea-with-ai",
    title: "Put Your Business Idea in Front of 5 AI Critics",
    promise: "Write the idea down in one paragraph, let five critics find the holes, and run a one-week test before you spend anything.",
    cover: "/images/guides/test-business-idea-with-ai.webp",
    coverAlt: "The blue robot mascot stamping a row of idea cards with ticks and crosses",
    seoDescription: "Asking AI \"is this a good idea?\" gets you encouragement. Ask five critics with different jobs to find the problems, then let real people answer the only question that counts: will they pay?",
    lumailTag: "guide-test-business-idea-with-ai",
    answer: { paragraphs: ["Asking AI \"is this a good idea?\" gets you encouragement. Ask five critics with different jobs to find the problems, then let real people answer the only question that counts: will they pay?"] },
    sections: [],
    conclusion: { heading: "", paragraphs: ["Write the idea down in one paragraph, let five critics find the holes, and run a one-week test before you spend anything."], finishLine: "" },
    related: [],
  },
  {
    slug: "weekend-projects-with-claude",
    title: "Weekend Projects: 7 Useful Things Claude Can Build",
    promise: "Small tools for real life, each built from a single description. Nothing to install, and nothing private inside.",
    cover: "/images/guides/weekend-projects-with-claude.webp",
    coverAlt: "The blue robot mascot building a small machine from gears, a drawer and a horn",
    seoDescription: "Claude can build small interactive tools, with buttons and lists you can click, straight from a description. Start with three for your home, then try the four after sign-up.",
    lumailTag: "guide-weekend-projects-with-claude",
    answer: { paragraphs: ["Claude can build small interactive tools, with buttons and lists you can click, straight from a description. Start with three for your home, then try the four after sign-up."] },
    sections: [],
    conclusion: { heading: "", paragraphs: ["Small tools for real life, each built from a single description. Nothing to install, and nothing private inside."], finishLine: "" },
    related: [],
  },
  {
    slug: "money-plan-with-ai",
    title: "Build a Money Plan From Your Payslip With AI",
    promise: "Understand every line on your payslip, split what's left into a plan you can live with, and check it once a month.",
    cover: "/images/guides/money-plan-with-ai.webp",
    coverAlt: "The blue robot mascot holding a checklist beside a balance of coins and receipts",
    seoDescription: "AI is good at explaining, adding up and organising. Give it your take-home pay and your regular costs (never your account details), and it can help you build a simple plan and check it each month. The decisions stay yours.",
    lumailTag: "guide-money-plan-with-ai",
    answer: { paragraphs: ["AI is good at explaining, adding up and organising. Give it your take-home pay and your regular costs (never your account details), and it can help you build a simple plan and check it each month. The decisions stay yours."] },
    sections: [],
    conclusion: { heading: "", paragraphs: ["Understand every line on your payslip, split what's left into a plan you can live with, and check it once a month."], finishLine: "" },
    related: [],
  },
  {
    slug: "ai-job-interview-practice",
    title: "Rehearse Any Job Interview With AI",
    promise: "Work out what they'll really test, practise one question at a time, and walk in with five stories ready.",
    cover: "/images/guides/ai-job-interview-practice.webp",
    coverAlt: "The blue robot mascot at a brass console with speech bubbles above it",
    seoDescription: "Nerves drop when you've practised out loud. AI can read the job ad for what they'll test, act as your interviewer one question at a time, and help you prepare stories that answer most questions.",
    lumailTag: "guide-ai-job-interview-practice",
    answer: { paragraphs: ["Nerves drop when you've practised out loud. AI can read the job ad for what they'll test, act as your interviewer one question at a time, and help you prepare stories that answer most questions."] },
    sections: [],
    conclusion: { heading: "", paragraphs: ["Work out what they'll really test, practise one question at a time, and walk in with five stories ready."], finishLine: "" },
    related: [],
  },
  {
    slug: "launch-your-product-in-30-days",
    title: "The 30-Day Checklist That Gets Your Product Out the Door",
    promise: "Cut the product to its smallest useful version, plan 4 weeks backwards from launch day, and check every Friday what's blocking you.",
    cover: "/images/guides/launch-your-product-in-30-days.webp",
    coverAlt: "The blue robot mascot watching a conveyor carry parcels from moon to sun",
    seoDescription: "Most products don't launch because they keep growing. Decide what the first version doesn't include, plan backwards from a fixed date, and let AI do the planning and the Friday check so you can spend your time making.",
    lumailTag: "guide-launch-your-product-in-30-days",
    answer: { paragraphs: ["Most products don't launch because they keep growing. Decide what the first version doesn't include, plan backwards from a fixed date, and let AI do the planning and the Friday check so you can spend your time making."] },
    sections: [],
    conclusion: { heading: "", paragraphs: ["Cut the product to its smallest useful version, plan 4 weeks backwards from launch day, and check every Friday what's blocking you."], finishLine: "" },
    related: [],
  },
  {
    slug: "marketing-emails-that-sell",
    title: "3 Email Rules That Make People Click Buy",
    promise: "Write to one person, make the subject line say what's inside, and let a real customer's words do the persuading.",
    cover: "/images/guides/marketing-emails-that-sell.webp",
    coverAlt: "The blue robot mascot sending envelopes through a line of brass pipes",
    seoDescription: "Most sales emails talk to everyone, hide what they're about and make big promises. Write to one real customer, say what's inside in the subject line, and show proof instead of promises. AI helps with drafts; you bring the customer and the proof.",
    lumailTag: "guide-marketing-emails-that-sell",
    answer: { paragraphs: ["Most sales emails talk to everyone, hide what they're about and make big promises. Write to one real customer, say what's inside in the subject line, and show proof instead of promises. AI helps with drafts; you bring the customer and the proof."] },
    sections: [],
    conclusion: { heading: "", paragraphs: ["Write to one person, make the subject line say what's inside, and let a real customer's words do the persuading."], finishLine: "" },
    related: [],
  },
];
