// Frozen migration allowlist. Existing guides may keep their current renderer until rebuilt.
// New guides must provide an approved interactive Next.js composition.
export const legacyGuideSlugs = new Set([
  "ai-skills-worth-learning-for-work",
  "chatgpt",
  "chatgpt-customer-research-with-evidence",
  "chatgpt-screen-recording-to-process-guide",
  "connect-ai-to-email-files-calendar",
  "control-kimi-code-changes",
  "copilot",
  "deepseek",
  "fix-gemini-workspace-action",
  "gemini",
  "grok",
  "is-mistral-pro-worth-it",
  "kimi",
  "manus",
  "manus-browser-workflow",
  "meta-ai",
  "mistral",
  "mistral-multilingual-research",
  "protect-a-long-deepseek-project",
  "show-up-in-ai-search",
  "switch-from-chatgpt-to-mistral",
  "teach-claude-a-repeatable-workflow",
  "test-deepseek-v4-document-work",
  "test-grok-repeated-image-edits",
  "test-manus-without-burning-credits",
  "test-meta-business-agent-customer-replies",
  "test-meta-muse-money-saving-task",
  "what-can-copilot-see-at-work",
  "what-is-an-ai-browser",
]);
